Task24_Middle/Models/Article.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Task24_Middle.Models
{
    public class Article
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public DateTime Date { get; set; }
        public string Text { get; set; }
    }
}

Task24_Middle/Models/FormData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Task24_Middle.Models
{
    public class FormData
    {
        public int Id { get; set; }
        public string Visit { get; set; }
        public string Satisfaction { get; set; }
        public string PrimaryUsing { get; set; }
        public string LevelOfService { get; set; }
    }
}

Task24_Middle/Models/LibraryDbContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace Task24_Middle.Models
{
    public class LibraryDbContext : DbContext
    {
        public DbSet<Article> Articles { get; set; }
        public DbSet<Review> Reviews { get; set; }
        public DbSet<FormData> FormsData { get; set; }

        public LibraryDbContext() : base("Library")
        {
            Database.SetInitializer<LibraryDbContext>(
                new CreateDatabaseIfNotExists<LibraryDbContext>());
        }

    }
}

Task24_Middle/Models/Review.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Task24_Middle.Models
{
    public class Review
    {
        public int Id { get; set; }
        [StringLength(20, MinimumLength = 2, ErrorMessage = "Name's length must be from 2 to 20 letters")]
        public string AuthorName { get; set; }
        [DataType(DataType.Date)]
        public DateTime Date { get; set; }
        public string Text { get; set; }
    }
}

Task24_Middle/Controllers/FormController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Task24_Middle;
using Task24_Middle.Models;

namespace Task24_Middle.Controllers
{
    public class FormController : Controller
    {
        /// <summary></summary>
        /// <returns>Page with survey</returns>
        [HttpGet]
        public ActionResult Form()
        {
            return View("FormPage");
        }
        /// <summary>
        /// Add new survey to database if data is valid
        /// </summary>
        /// <param name="data"></param>
        /// <returns>Redirect to GET method "FormPage" </returns>
        [HttpPost]
        public ActionResult FormPage(FormData data)
        {
            if (String.IsNullOrEmpty(data.LevelOfService))
                ModelState.AddModelError("LevelOfService", 
                    "Please choise a level of service");

            if (String.IsNullOrEmpty(data.PrimaryUsing))
                ModelState.AddModelError("PrimaryUsing", 
                    "Please tell about your primary using of this library");

            if (String.IsNullOrEmpty(data.Satisfaction))
                ModelState.AddModelError("Satisfaction", 
                    "Please choise your satisfation level");

            if (String.IsNullOrEmpty(data.Visit))
                ModelState.AddModelError("Visit", 
                    "Please say how often do you visit library");

            var uof = new UnitOfWork();

            if (ModelState.IsValid)
            {
                uof.FormRepo.Add(data);
                return RedirectToAction("FormPage");
            }
            else
                return View("FormPage");

        }
        
        /// <summary></summary>
        /// <returns>View of page with results of surveys</returns>
        [HttpGet]
        public ActionResult FormPage()
        {
            var uof = new UnitOfWork();
            return View("FormPageResult", uof.FormRepo.GetAll());
        }
    }
}

Task24_Middle/Controllers/GuestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Task24_Middle.Models;

namespace Task24_Middle.Controllers
{
    public class GuestController : Controller
    {
        /// <summary></summary>
        /// <returns>A view of page with reviews</returns>
        [HttpGet]
        public ActionResult GuestPage()
        {
            var uow = new UnitOfWork();
            return View(uow.RevRepo.GetAll());
        }

        /// <summary>
        /// Add new review to database if data is valid
        /// </summary>
        /// <param name="review"></param>
        /// <returns>A view of page with reviews</returns>
        [HttpPost]
        public ActionResult AddReview(Review review)
        {
            if (string.IsNullOrEmpty(review.Text))
            {
                ModelState.AddModelError("Text", "You did not enter your review");
            }
            
            if (string.IsNullOrEmpty(review.AuthorName))
            {
                ModelState.AddModelError("AuthorName", "You have to enter your name");
            }
            var uow = new UnitOfWork();
            if (ModelState.IsValid)
                uow.RevRepo.Add(review);
            return View("GuestPage", uow.RevRepo.GetAll());
        }
    }
}

Task24_Middle/Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Task24_Middle.Models;

namespace Task24_Middle.Controllers
{
    public class MainController : Controller
    {
        /// <summary></summary>
        /// <returns>A view of main page</returns>
        public ActionResult MainPage()
        {
            var uow = new UnitOfWork();
            return View(uow.ArticlRepo.GetAll());
        }
    }
}

Task24_Middle/Views/Form/FormPage.cshtml
@model Task24_Middle.Models.FormData
@{
    ViewBag.Title = "Form Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/Content/Site.css" rel="stylesheet" type="text/css"/>

<div id="form">
    @using (Html.BeginForm("FormPage", "Form", FormMethod.Post))
    {
        @Html.ValidationSummary(true)
    <div class="form-group">
        <h2 class="text-center">How ofter do you visit the library?</h2>
        @Html.ListBoxFor(m => m.Visit, new MultiSelectList(
                           new string[] { "Monthly", "Weekly", "Daily" }),
                           new { @class = "form-control" })
        <p class="alert-danger">@Html.ValidationMessageFor(m => m.Visit)</p>
    </div>
    <div class="form-group">
        <h2 class="text-center">
            How satisfied are you with the
            opening hours of the library?
        </h2>
        @Html.ListBoxFor(m => m.Satisfaction, new MultiSelectList(
                      new string[] {"Satisfied", "Indiffirent",
                    "Dissatisfied"}), new { @class = "form-control" })
        <p class="alert-danger">@Html.ValidationMessageFor(m => m.Satisfaction)</p>
    </div>
    <div class="form-group">
        <h2 class="text-center">
            Rate our services
        </h2>
        @Html.ListBoxFor(m => m.LevelOfService, new MultiSelectList(
                            new string[] {"Excelent", "Very good", "Sufficient",
                    "Insufficient"}), new { @class = "form-control" })
        <p class="alert-danger">@Html.ValidationMessageFor(m => m.LevelOfService)</p>
    </div>
    <div class="form-group">
        <h2 class="text-center">
            Why do you primarily use the library
            and its services?
        </h2>
        @Html.ListBoxFor(m => m.PrimaryUsing, new MultiSelectList(
                                 new string[] { "Leisure", "Education", "Work" }),
                                     new { @class = "form-control" })
        <p class="alert-danger">@Html.ValidationMessageFor(m => m.PrimaryUsing)</p>
    </div>
    <button type="submit" class="btn btn-primary form-control">Send</button>
    }
</div>

Task24_Middle/Views/Form/FormPageResult.cshtml
@model IEnumerable<Task24_Middle.Models.FormData>
@using Task24_Middle.ExtensionMethods

@{ 
    ViewBag.Title = "Result of form";
    Layout = "~/Views/Shared/_Layout.cshtml"; 
}

<link href="~/Content/Site.css" rel="stylesheet" type="text/css" />

@Html.DrawResults(Model)

Task24_Middle/Views/Guest/GuestPage.cshtml
@using Task24_Middle.Models
@model IEnumerable<Review>
@{
    ViewBag.Title = "GuestPage";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/Content/Site.css" rel="stylesheet" type="text/css" />

<div id="reviews">
    @foreach (var review in Model)
    {
<div class="article">
    <p>@review.AuthorName:</p>
    <p>@review.Date</p>
    <p>@review.Text</p>
</div>}
    @using (Html.BeginForm("AddReview", "Guest", FormMethod.Post))
    {
        @Html.ValidationSummary(true)
        <div class="form-group">
            <input type="hidden" value=@DateTime.Now.ToShortDateString() name="date" />
            <p>Enter your name</p>
            @Html.TextBox("AuthorName", "", new { @class = "form-control" })
            <p class="alert-danger">@Html.ValidationMessageFor(m => m.Single().AuthorName)</p>
        </div>
        <div class="form-group">
            <p>Enter your review</p>
            @Html.TextArea("Text", new { @class="form-control" })
            <p class="alert-danger">@Html.ValidationMessageFor(m => m.Single().Text)</p>
            <input class="btn btn-primary form-control" type="submit" value="Send" />
        </div>
    }
</div>

Task24_Middle/Views/Main/MainPage.cshtml
@model IEnumerable<Task24_Middle.Models.Article>
@{
    ViewBag.Title = "Main Page";
}

<link href="~/Content/Site.css" rel="stylesheet" type="text/css" />

@foreach(var article in Model) 
{ 
    <div class="list-group">
        <h2>@article.Name</h2>
        <h3>@article.Date.ToShortDateString()</h3>
        <h4>@article.Text</h4>
    </div>
}

Task24_Middle/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href=@Url.Content("~/Content/Site.css") type="text/css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <main>
        <h1 class="text-center">
            <img alt="logo" src="~/logo.png" class="logo" />
            Library "Task23_Middle"
        </h1>
    </main>
    <div id="content" class="row">
        <div id="left" class="col-md-8">
            @RenderBody()
        </div>
        <div id="menu" class="col-md-2">
            <ul class="nav nav-stacked nav-pills text-center">
                <li><a href="/Main/MainPage">Main page</a></li>
                <li><a href="/Guest/GuestPage">Guest page</a></li>
                <li><a href="/Form/Form">Form page</a></li>
            </ul>
        </div>
    </div>
    <br />
    <footer>
        <p class="text-center">
            Copyright &copy; @DateTime.Now.Year. All Rights Reserved.
            Maksym Kot
            <a href="#" class="text-center" id="up">To Top</a>
        </p>
        <script src="~/Scripts/up.js"></script>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>